### ISSUE TITLE
[Bug]: Server Mods not getting copied

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#453]
### What happened?

In the last few builds when I do my first test run, often server mods are missing. The server does not start due to missing dependencies

### What did you expect to happen?

All mods except for those in the Clientside mod list are to be copied to the server mods folder

### Version

4.0.1

### Relevant log output
[modloader_installer.log](https://github.com/Griefed/ServerPackCreator/files/10997168/modloader_installer.log)
[serverpackcreator.log](https://github.com/Griefed/ServerPackCreator/files/10997169/serverpackcreator.log)

### Anything else you would like to add?

In this last case, it was the mods, Patchouli-1.18.2-71.1.jar and Incorporeal-3-forge-1.18.2-5.jar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya ClaudiusMinimus,

thanks for opening this issue and for including the serverpackcreator.log!

I can confirm that both, Incorporeal-3-forge-1.18.2-5.jar and Patchouli-1.18.2-71.1.jar, should be included, as per their mods.toml definitions.

```toml
modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/incorporeal-3/issues"
logoFile = "wide_lores_banner.png"

[[mods]]
modId = "incorporeal"
version = "1.18.2-5"
displayName = "Incorporeal 3"
description = "Addon to a magic mod. More toys for Botania corporea dorks."
authors = "quaternary"
credits = "artemisSystem, Dudblockman, SnazzGass, jaredlll08, Darkhax, all the Botania nerds, and everyone who puts up with me"

[[dependencies.incorporeal]]
modId="forge"
mandatory=true
versionRange="[40.0.35,)"

[[dependencies.incorporeal]]
modId="botania"
mandatory=true
ordering="AFTER"
versionRange="*"
```

```toml
modLoader="javafml"
license="CC BY-NC-SA 3.0"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Vazkii/Patchouli"
logoFile="logo.png"

[[mods]]
modId="patchouli"
displayName="Patchouli"
version="${file.jarVersion}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.patchouli]]
modId="forge"
mandatory=true
versionRange="[40.1.51,)"
```

So this is definitely a bug in the autodetection-system. I'll fix it in the coming days.
In the meantime, you may include them in your server pack by either

1. [Deactivating the autodetection-system](https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help#automatic-detection-of-clientside-only-mods), or
2. Specifying them as files to be included, which will override the auto-exclusion, using `mods/Patchouli-1.18.2-71.1.jar;mods/Patchouli-1.18.2-71.1.jar` and `mods/Incorporeal-3-forge-1.18.2-5.jar;mods/Incorporeal-3-forge-1.18.2-5.jar`

Cheers,
Griefed
