### ISSUE TITLE
[Clientside-mod Addition Request]: fast-ip-ping

### ISSUE THREAD

**Issue by ModernGamingWorld** [Griefed/ServerPackCreator#512]
### The link to the project on CurseForge or Modrinth

https://www.curseforge.com/minecraft/mc-mods/fast-ip-ping

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya,

fast-ip-ping specifies itself as  clientside-only in both Forge and Fabric:

```toml
modLoader = "javafml"
loaderVersion = "[31,)"
license = "LGPLv3"

[[mods]]
modId = "fastipping"
version = "1.0.1"
displayName = "Fast IP Ping"
displayURL = "https://github.com/Fallen-Breath/fast-ip-ping"
authors = "Fallen_Breath"
description = '''
Yeet the laggy reversed DNS lookup for pure IP server addresses
'''
logoFile = "icon.png"

[[dependencies."fastipping"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19, 1.19.4]"
ordering = "NONE"
side = "CLIENT"

```

```json
{
  "schemaVersion": 1,
  "id": "fastipping",
  "version": "1.0.1",

  "name": "Fast IP Ping",
  "description": "Yeet the laggy reversed DNS lookup for pure IP server addresses",
  "authors": [
    "Fallen_Breath"
  ],
  "contact": {
    "homepage": "https://modrinth.com/mod/fast-ip-ping",
    "sources": "https://github.com/Fallen-Breath/fast-ip-ping"
  },

  "icon": "assets/fastipping/icon.png",

  "environment": "client",
  "entrypoints": {
    "main": [
      "me.fallenbreath.fastipping.FastIpPingMod"
    ]
  },
  "mixins": [
    "fastipping.mixins.json"
  ],

  "depends": {
    "fabricloader": ">=0.11.4",
    "minecraft": "1.20.x"
  }
}
```

It's possible that the Forge-specification isn't enough to successfully exclude it, as it has the Forge-sideness missing. That'd be an error on the mod creators side. Task failed successfully :D If it's not excluded automatically, then I suggest pinging the author so they can fix this, as they are already almost there.

Cheers,
Griefed
